#ifndef _TEST_SERVER_H_
#define _TEST_SERVER_H_

#define	HELLO_SVR_CMD_SAYHELLO 0
#define	HELLO_SVR_CMD_SAYHELLO_TO 1

#define	GOODBYE_SVR_CMD_SAYGOODBYE 2
#define	GOODBYE_SVR_CMD_SAYGOODBYE_TO 3

#endif //_TEST_SERVER_H_
